### PR TITLE
Solve.py

### PR DESCRIPTION
**Pull request by shehabgamaleldeen**
printing the Sudoku board with a nice design

### CODE REVIEW

**Review by Boodyahmedhamdy — APPROVED** [review]
very good work, but next time you would add a new function `printRealBoard(board)` instead of deleting the existing one or changing it's paremeters

Great Job, Sensi

**Review by Boodyahmedhamdy — APPROVED** [review]
very good work, but next time you would add a new function `printRealBoard(board)` instead of deleting the existing one or changing it's paremeters

Great Job, Sensi

**Review by Boodyahmedhamdy — APPROVED** [review]
very good work, but next time you would add a new function `printRealBoard(board)` instead of deleting the existing one or changing it's paremeters

Great Job, Sensi

**Comment by shehabgamaleldeen** [comment]
Ok💪

‫في السبت، 17 ديسمبر 2022 في 11:33 ص تمت كتابة ما يلي بواسطة ‪Abdelrahman
Ahmed Hamdy‬‏ ***@***.***‬‏>:‬

**Pull request merged**
